spring.application.name=training-center-boot

#????????? ??? ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/training_center
spring.datasource.username=postgres
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ????????? ???? ??? ??????? ? ???????? JWT token - ??? HS256 ???? ?????? ???? ??????? 32 ???????
jwt.secret=mySuperSecretKeyForJwtTokenGeneration123456789

# ????? ????? JWT token ? ????????????? (86400000 = 24 ????)
jwt.expiration=86400000